CREATE TYPE favorite_color_enum AS ENUM (
  'red',
  'blue',
  'green',
  'other'
);

CREATE
OR REPLACE FUNCTION set_updated_at () RETURNS TRIGGER AS $$
BEGIN
NEW.updated_at = now();
RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';

CREATE TABLE individuals (
    individual_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    individual_uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    favorite_color favorite_color_enum,
    created_at timestamp without time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

INSERT INTO individuals (favorite_color, updated_at) VALUES ('red', '2020-01-01');
INSERT INTO individuals (favorite_color, updated_at) VALUES ('blue', '2020-01-01');
INSERT INTO individuals (favorite_color, updated_at) VALUES ('other', '2020-01-01');


-- Indices -------------------------------------------------------

CREATE INDEX idx_individuals_updated_at ON individuals(updated_at timestamptz_ops);

-- Triggers -------------------------------------------------------

CREATE TRIGGER individuals_setupdate
  BEFORE UPDATE ON public.individuals
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE address_types (
    address_type_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE UNIQUE,
    created_at timestamp without time zone NOT NULL DEFAULT timezone('utc'::text, now())
);

-- DDL generated by Postico 2.0.5
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE individual_addresses (
    individual_address_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    individual_id bigint NOT NULL REFERENCES individuals(individual_id),
    address_uuid uuid NOT NULL,
    address_type_id integer REFERENCES address_types(address_type_id),
    created_at timestamp without time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    deleted_at timestamp without time zone,
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX address_by_individual ON individual_addresses(individual_id int8_ops,address_type_id int4_ops) WHERE deleted_at IS NULL;
CREATE INDEX idx_addresses_updated_at ON individual_addresses(updated_at timestamptz_ops);

-- Triggers -------------------------------------------------------

CREATE TRIGGER addresses_setupdate
  BEFORE UPDATE ON public.individual_addresses
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

INSERT INTO address_types (name) VALUES ('home');
INSERT INTO address_types (name) VALUES ('office');

INSERT INTO individual_addresses (individual_id, address_uuid, address_type_id) VALUES (1, gen_random_uuid(), 1);
INSERT INTO individual_addresses (individual_id, address_uuid, address_type_id) VALUES (1, gen_random_uuid(), 2);
INSERT INTO individual_addresses (individual_id, address_uuid, address_type_id) VALUES (3, gen_random_uuid(), 1);
